// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoNJ_HuyNGQSYNX8b5le4s4h2NHnvE1XA',
    appId: '1:526782651221:web:7a0dfb9ed13fbe86f86ddc',
    messagingSenderId: '526782651221',
    projectId: 'wizzchat-30f09',
    authDomain: 'wizzchat-30f09.firebaseapp.com',
    storageBucket: 'wizzchat-30f09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneYEykUKMEEVjeA_FCmjXl0AGHzhafds',
    appId: '1:526782651221:android:2e32bbec58ce2ddbf86ddc',
    messagingSenderId: '526782651221',
    projectId: 'wizzchat-30f09',
    storageBucket: 'wizzchat-30f09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9rhHiuPMZgMH0vAmrbfOB81zwA2bpSbE',
    appId: '1:526782651221:ios:1628e8f705deffcef86ddc',
    messagingSenderId: '526782651221',
    projectId: 'wizzchat-30f09',
    storageBucket: 'wizzchat-30f09.firebasestorage.app',
    iosBundleId: 'com.example.wizzchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9rhHiuPMZgMH0vAmrbfOB81zwA2bpSbE',
    appId: '1:526782651221:ios:1628e8f705deffcef86ddc',
    messagingSenderId: '526782651221',
    projectId: 'wizzchat-30f09',
    storageBucket: 'wizzchat-30f09.firebasestorage.app',
    iosBundleId: 'com.example.wizzchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoNJ_HuyNGQSYNX8b5le4s4h2NHnvE1XA',
    appId: '1:526782651221:web:e161170aba51fb6af86ddc',
    messagingSenderId: '526782651221',
    projectId: 'wizzchat-30f09',
    authDomain: 'wizzchat-30f09.firebaseapp.com',
    storageBucket: 'wizzchat-30f09.firebasestorage.app',
  );
}